"""
[claude] Spreadsheet reader — worksheets, typed columns, and every row.

This reader keeps all the rows, not a sample. That is the point of it: the
agent compares uploaded figures against CRM figures, and a comparison built
on a sample is a guess. Retrieval decides *which* rows are worth looking at;
this content is what makes the arithmetic over them exact.

Inference, kept coarse
----------------------
A spreadsheet has no schema. The header row is a naming convention, not a
declaration, and the values below it may be numbers, text that looks like
numbers, or both in the same column. So `dtype` is one of three labels —
"number", "date", "text" — and a column earns "number" only when *every*
non-empty value in it parses as one. A column that is 95% numeric is text
with numbers in it, and calling it numeric is how you end up summing a
column that contains "N/A" as though it were zero.
"""

from __future__ import annotations

import csv
import math
from datetime import date, datetime, time
from decimal import Decimal, InvalidOperation
from itertools import chain
from pathlib import Path

from openpyxl import load_workbook

from app.workspace.models import ColumnSpec, FileKind, ParsedFile, SheetContent

# [claude] Row ceiling per worksheet. A workspace is for reconciliation, not
# bulk import: 100k rows is far past the point where the answer should come
# from the CRM instead. Truncation is reported, never silent.
MAX_ROWS_PER_SHEET = 100_000

# Guard against a spreadsheet with thousands of junk columns to the right of
# the real data, which openpyxl will happily report as dimensions.
MAX_COLUMNS = 256

# Long free-text cells (a notes column) are capped so one row cannot consume
# the payload budget of a tool result.
MAX_CELL_CHARS = 2_000

# How far to look for the header row. Generous enough for a title block and a
# few notes above the table, small enough that it cannot latch onto a data row
# deep in a file whose real header is genuinely sparse.
HEADER_SCAN_ROWS = 20


def read_spreadsheet(
    path: Path,
    display_name: str | None = None,
) -> tuple[ParsedFile, tuple[str, ...]]:
    """
    Parse a spreadsheet or delimited text file into worksheets.

    `display_name` is the name the user uploaded, used to name the single
    sheet of a delimited file. A workbook carries its own sheet names and
    ignores it.
    """

    suffix = path.suffix.lower()

    if suffix in {".csv", ".tsv"}:
        sheets, warnings = _read_delimited(path, suffix, display_name)
    else:
        sheets, warnings = _read_workbook(path)

    if not sheets:
        raise ValueError("This spreadsheet has no readable worksheets.")

    return (
        ParsedFile(kind=FileKind.SPREADSHEET, sheets=tuple(sheets)),
        tuple(warnings),
    )


# ============================================================
# Excel
# ============================================================


def _read_workbook(path: Path) -> tuple[list[SheetContent], list[str]]:
    warnings: list[str] = []

    # read_only streams rather than building the whole object graph.
    # data_only returns the cached result of a formula instead of "=A1+B1".
    workbook = load_workbook(filename=str(path), read_only=True, data_only=True)

    sheets: list[SheetContent] = []

    try:
        for worksheet in workbook.worksheets:
            rows = worksheet.iter_rows(values_only=True)

            sheet, sheet_warnings = _build_sheet(
                name=str(worksheet.title),
                rows=rows,
            )

            warnings.extend(sheet_warnings)

            if sheet is not None:
                sheets.append(sheet)
    finally:
        workbook.close()

    # [claude] data_only gives None for every formula cell when the file was
    # written by a library rather than by Excel — the cached values simply
    # are not there. An all-empty numeric-looking sheet is the symptom, so
    # say so rather than letting the agent report a file full of blanks.
    if sheets and all(sheet.row_count == 0 for sheet in sheets):
        warnings.append(
            "No data rows were found. If this file was generated by a "
            "program rather than saved from Excel, formula results may not "
            "be stored in it."
        )

    return sheets, warnings


# ============================================================
# CSV / TSV
# ============================================================


def _read_delimited(
    path: Path,
    suffix: str,
    display_name: str | None = None,
) -> tuple[list[SheetContent], list[str]]:
    warnings: list[str] = []

    # [claude] utf-8-sig strips the BOM Excel writes when it exports CSV,
    # which would otherwise become part of the first column's name and make
    # that column unaddressable by the name the user can see.
    for encoding in ("utf-8-sig", "cp1252", "latin-1"):
        try:
            text = path.read_text(encoding=encoding)
            break
        except UnicodeDecodeError:
            continue
    else:
        raise ValueError("Could not decode this file as text.")

    if encoding != "utf-8-sig":
        warnings.append(
            f"File was not valid UTF-8; decoded as {encoding}. "
            "Accented or non-Latin characters may be wrong."
        )

    delimiter = "\t" if suffix == ".tsv" else _sniff_delimiter(text)

    reader = csv.reader(text.splitlines(), delimiter=delimiter)

    # A delimited file has no internal sheet name, so it borrows the
    # uploaded filename. Falling back to path.stem would name the sheet after
    # the opaque storage id, which is what the user would then be told.
    name = Path(display_name).stem if display_name else path.stem

    sheet, sheet_warnings = _build_sheet(name=name, rows=reader)
    warnings.extend(sheet_warnings)

    return ([sheet] if sheet is not None else []), warnings


def _sniff_delimiter(text: str) -> str:
    """Pick a delimiter from the header line, defaulting to a comma."""

    header = text.splitlines()[0] if text.splitlines() else ""

    try:
        return csv.Sniffer().sniff(header, delimiters=",;\t|").delimiter
    except csv.Error:
        return ","


# ============================================================
# Shared construction
# ============================================================


def _build_sheet(name, rows) -> tuple[SheetContent | None, list[str]]:
    """Turn an iterable of raw row tuples into a typed SheetContent."""

    warnings: list[str] = []

    iterator = iter(rows)

    header, iterator, skipped = _find_header(iterator)

    if header is None:
        warnings.append(f"Worksheet {name!r} is empty and was skipped.")
        return None, warnings

    if skipped:
        warnings.append(
            f"Worksheet {name!r}: skipped {skipped} row(s) above the header."
        )

    if len(header) > MAX_COLUMNS:
        header = header[:MAX_COLUMNS]
        warnings.append(
            f"Worksheet {name!r} was read as its first {MAX_COLUMNS} columns."
        )

    column_names = _normalise_header(header)

    records: list[dict[str, object]] = []
    truncated = False

    for raw_row in iterator:
        if len(records) >= MAX_ROWS_PER_SHEET:
            truncated = True
            break

        values = list(raw_row[: len(column_names)])

        # Trailing short rows are normal in exported sheets.
        values.extend([None] * (len(column_names) - len(values)))

        if all(_is_blank(value) for value in values):
            continue

        records.append(
            {
                column: _coerce(value)
                for column, value in zip(column_names, values, strict=True)
            }
        )

    if truncated:
        warnings.append(
            f"Worksheet {name!r} was truncated at {MAX_ROWS_PER_SHEET:,} rows."
        )

    columns = tuple(
        _infer_column(column, records) for column in column_names
    )

    return (
        SheetContent(name=str(name), columns=columns, rows=tuple(records)),
        warnings,
    )


def _find_header(iterator) -> tuple[tuple | None, object, int]:
    """
    Locate the header row, skipping any title rows above it.

    Returns (header, remaining_rows, rows_skipped).

    [claude] This used to take the first row containing anything at all, and
    a real export immediately broke it. A sales tracker opens like this:

        A1: "MarQ Sales — Q3 Unit Tracker (internal)"     <- one cell
        A2: (blank)
        A3: Deal ID | Client Name | Unit Number | ...     <- seven cells

    The old rule named column 1 after the report title and columns 2-7
    `column_2`...`column_7`, so every column in the file became unaddressable
    and `sum` over "Area (sqm)" failed with "no such column". The unit test
    covered leading *blank* rows and missed this entirely — the docstring
    even described the failure while the code did not handle it.

    The rule: measure the widest row in the first HEADER_SCAN_ROWS, then take
    the first row at least half that wide. A title spans one cell while the
    table spans many, so the title is skipped and the header is not.

    "Widest row wins" was the obvious rule and is wrong — it picks a data row
    over its own header whenever the header has a blank column. `id,,id`
    above `1,2,3` is two populated cells against three, and the data row
    would become the column names. Half-width-then-earliest keeps both cases:

        title(1) blank(0) header(7) data(7)  -> header, 1 skipped
        header(2)         data(3)            -> header, 0 skipped
        header(1)         data(1)            -> header (single column)
    """

    window: list[tuple] = []

    for row in iterator:
        if row is None:
            continue

        window.append(tuple(row))

        if len(window) >= HEADER_SCAN_ROWS:
            break

    counts = [
        sum(1 for value in row if not _is_blank(value)) for row in window
    ]

    widest = max(counts, default=0)

    if widest == 0:
        return None, iter(()), 0

    best_index = next(
        index
        for index, count in enumerate(counts)
        if count * 2 >= widest
    )

    remaining = chain(window[best_index + 1 :], iterator)

    # Only non-blank rows above the header are worth reporting; leading blank
    # lines are ordinary and mentioning them would be noise.
    skipped = sum(
        1
        for row in window[:best_index]
        if any(not _is_blank(value) for value in row)
    )

    return window[best_index], remaining, skipped


def _normalise_header(header: tuple) -> list[str]:
    """
    Produce usable, unique column names.

    Blank headers become positional names rather than empty strings, and
    duplicates are suffixed, so every column can be referred to unambiguously
    by the agent.
    """

    names: list[str] = []
    seen: dict[str, int] = {}

    for position, value in enumerate(header, start=1):
        name = "" if _is_blank(value) else str(value).strip()

        if not name:
            name = f"column_{position}"

        if name in seen:
            seen[name] += 1
            name = f"{name}_{seen[name]}"
        else:
            seen[name] = 1

        names.append(name)

    return names


def _infer_column(name: str, records: list[dict[str, object]]) -> ColumnSpec:
    """Label a column by what every one of its values actually is."""

    values = [
        record[name]
        for record in records
        if not _is_blank(record.get(name))
    ]

    if not values:
        return ColumnSpec(name=name, dtype="empty", non_null=0)

    if all(
        isinstance(value, (int, float)) and not isinstance(value, bool)
        for value in values
    ):
        dtype = "number"
    elif all(_looks_like_date(value) for value in values):
        dtype = "date"
    elif all(_parses_as_number(value) for value in values):
        # [claude] Numbers that arrived as text — every CSV column is text on
        # the way in. Labelled distinctly so the agent knows a cast is
        # involved, mirroring catalogue rule 22 on the CRM side, where
        # `area` is varchar and has to be cast before it can be ordered.
        dtype = "numeric_text"
    else:
        dtype = "text"

    return ColumnSpec(name=name, dtype=dtype, non_null=len(values))


# ============================================================
# Values
# ============================================================


def _is_blank(value) -> bool:
    if value is None:
        return True

    if isinstance(value, str):
        return not value.strip()

    if isinstance(value, float):
        return math.isnan(value)

    return False


def _coerce(value):
    """
    Make a cell JSON-serialisable without changing what it means.

    Dates become ISO strings and Decimals become floats; everything else is
    left exactly as read. Notably, text is *not* parsed into numbers here —
    that would discard the distinction between 007 and 7, which matters for
    reference codes, and it is the kind of silent normalisation that makes a
    comparison against the CRM disagree for reasons nobody can see.
    """

    if value is None:
        return None

    if isinstance(value, bool):
        return value

    if isinstance(value, (datetime, date, time)):
        return value.isoformat()

    if isinstance(value, Decimal):
        return float(value)

    if isinstance(value, float) and math.isnan(value):
        return None

    if isinstance(value, str):
        stripped = value.strip()

        if len(stripped) > MAX_CELL_CHARS:
            return stripped[:MAX_CELL_CHARS] + "…"

        return stripped

    if isinstance(value, (int, float)):
        return value

    return str(value)


def _parses_as_number(value) -> bool:
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return True

    if not isinstance(value, str):
        return False

    candidate = value.strip().replace(",", "").replace("%", "")

    if not candidate:
        return False

    try:
        Decimal(candidate)
    except (InvalidOperation, ValueError):
        return False

    return True


def _looks_like_date(value) -> bool:
    if not isinstance(value, str):
        return False

    try:
        datetime.fromisoformat(value)
    except ValueError:
        return False

    return True


__all__ = [
    "HEADER_SCAN_ROWS",
    "MAX_CELL_CHARS",
    "MAX_COLUMNS",
    "MAX_ROWS_PER_SHEET",
    "read_spreadsheet",
]
